export const cartActionTypes = {
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  TOGGLE_HIDDEN: "TOGGLE_HIDDEN",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
  CHECKOUT_START: "CHECKOUT_START",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCESS",
  CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
  CLEAR_CHECKOUT_MESSAGE: "CLEAR_CHECKOUT_MESSAGE",
  SET_LOADING: "SET_LOADING",
  ADD_TO_CART_CLICK: "ADD_TO_CART_CLICK",
};
